# name of the workflow
name: deploy-container

# which events do we watch for
on:
  workflow_dispatch:
  push:
    branches:
      - master
    # watch for changes on specific files
    paths:
      - 'container/**'

# so that we don't have to 'cd container' on each step
defaults:
  run:
    working-directory: container

jobs:
  # name of the job
  build:
    runs-on: ubuntu-latest
    steps:
      # loads/checkouts all the code inside this temp container to run all the steps
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - name: S3 Sync
        # gives access to aws cli
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync container/dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'

      # - name: S3 invalidation for index.hmtl
      #   # gives access to aws cli
      #   uses: ItsKarma/aws-cli@v1.70.0
      #   with:
      #     args: cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "container/latest/index.html"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: 'ap-south-1'
      # - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "container/latest/index.html"
      - name: Configure AWS credentials for invalidation
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'

      - name: S3 invalidation for index.html
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "container/latest/index.html"
